### ISSUE TITLE
Outdated submodule openmaptiles

### ISSUE THREAD

**Issue by jpbede** [makinacorpus/makina-maps#11]
Hey

the `openmaptiles` submodule seems to be outdated:

```Fetched in submodule path 'openmaptiles', but it did not contain c46cebacfbfe4b8a20cbeb621e95d14f5651fdaf. Direct fetching of that commit failed.```

Which branch of the fork is the right one ?

**Comment by frodrigo** [comment]
Sorry not synch between project. Fixed now. Update makina-maps and openmaptiles
