### ISSUE TITLE
Error import-sql (Extract script)

### ISSUE THREAD

**Issue by toinouu** [makinacorpus/makina-maps#13]
Hi

I have this error when I launch 30-import-extract.sh

`
psql:/sql/tileset.sql:2475: NOTICE: Processing layer building
DO
Time: 0.556 ms
psql:/sql/tileset.sql:2492: ERROR: function regexp_match(text, unknown) does not exist
LINE 5: (REGEXP_MATCH(
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
Time: 1.556 ms
make: *** [Makefile:117: import-sql] Error 3
`

**Comment by frodrigo** [comment]
Thank you for report. I fixed it but not pushed yet. The remote docker image have changed.
You have to revert this commit on OpenMapTiles
https://github.com/frodrigo/openmaptiles/commit/80b60867207cc0b6aaf8db3c9f9c0efe8e19e244

**Comment by toinouu** [comment]
It works !

Could you push this ?  :)

**Comment by frodrigo** [comment]
It is done (makina-maps and openmaptiles fork update)
