### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by toinouu** [makinacorpus/makina-maps#14]
Hey,

I just updated the project.
When I start the project (docker-compise up), all the containers launch correctly but I can't see the map, I have an error 500
![image](https://user-images.githubusercontent.com/503587/80947622-d7c68300-8df0-11ea-81c1-70a5ceb010ad.png)

Thanks for your help

**Comment by frodrigo** [comment]
Look at server logs first.

**Comment by toinouu** [comment]
`
/data/expire_tiles/???????; No such file or directory
`

**Comment by frodrigo** [comment]
This is not an issue. You does not have `expire_tiles` until your update the OSM data and effectively got tiles to expire.

Check the logs of the 4 components: makina-maps_nginx_1, makina-maps_tileserver-gl_1, openmaptiles_postserve_1, openmaptiles_postgres_1

**Comment by toinouu** [comment]
sudo docker logs makina-maps_nginx_1

`
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 19501 100 19501 0 0 1190k 0 --:--:-- --:--:-- --:--:-- 1190k
EXPIRE SOURCE: bright v3
Setting up watches. Beware: since -r was given, this may take a while!
Watches established.
find: /data/expire_tiles/????????: No such file or directory
`

sudo docker logs makina-maps_tileserver-gl_1

`
INFO:tornado.access:200 GET / (172.19.0.3) 4.85ms
INFO:tornado.access:200 GET / (172.19.0.3) 0.78ms
`
`
/usr/local/lib/python3.8/site-packages/asyncpg/connection.py:1329: InterfaceWarning: <asyncpg.connection.Connection object at 0x7fd4a7ac75f0> is being released to the pool but has 1 active log listener
warnings.warn(w)
ERROR:tornado.application:Uncaught exception GET /tiles/3/4/2.pbf (172.19.0.5)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/tiles/3/4/2.pbf', version='HTTP/1.0', remote_ip='172.19.0.5')
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/usr/src/app/openmaptiles/postserve.py", line 81, in get
tile = await connection.fetchval(query, zoom, x, y)
File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 439, in fetchval
data = await self._execute(query, args, 1, timeout)
File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1413, in _execute
result, _ = await self.__execute(
File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1422, in __execute
return await self._do_execute(query, executor, timeout)
File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1434, in _do_execute
stmt = await self._get_statement(query, None)
File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 329, in _get_statement
statement = await self._protocol.prepare(stmt_name, query, timeout)
File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.UndefinedFunctionError: function st_asmvt(unknown, integer, unknown, record) does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
`

sudo docker logs openmaptiles_postgres_1

`ERROR: canceling autovacuum task
CONTEXT: automatic analyze of table "openmaptiles.public.osm_ocean_polygon_gen3"
ERROR: canceling autovacuum task
CONTEXT: automatic analyze of table "openmaptiles.public.osm_ocean_polygon_gen4"
ERROR: canceling autovacuum task
CONTEXT: automatic analyze of table "openmaptiles.public.osm_ocean_polygon_gen1`

**Comment by frodrigo** [comment]
Th error is
```
function st_asmvt(unknown, integer, unknown, record) does not exist
```
This function is provided by postgis.

**Comment by toinouu** [comment]
it's a postgis version problem?

**Comment by toinouu** [comment]
it works if i replace 
  
image: "openmaptiles/postgis:build-5.0-dev" =>  image: "openmaptiles/postgis:${TOOLS_VERSION}"

in docker-compose from openmaptiles

**Comment by frodrigo** [comment]
Ok. So it is an other issue linked to the remote change of the docker images.

**Comment by frodrigo** [comment]
I commit this change to have a working setup on master. But note the OSM update is not working for now with this docker changes.
