### ISSUE TITLE
Static map

### ISSUE THREAD

**Issue by toinouu** [makinacorpus/makina-maps#16]
Hey,

I just tested  creation of static map 
=> https://tileserver.readthedocs.io/en/latest/endpoints.html

But I always have the same result an empty image.
When I try with an mbTiles file I don't have the problem

![image](https://user-images.githubusercontent.com/503587/81391815-02c91380-911e-11ea-9a15-a8ed57d6d425.png)

Do you have any idea where the problem come from ?

Thank you

**Comment by frodrigo** [comment]
I push the update of Makina Maps and OpenMapTiles fork.Please test with this new version.

**Comment by toinouu** [comment]
I have been trying to do a new installation from the start.

I got an error when I try to run script 20 "prepare"


Getting content length for https://download.geofabrik.de/europe/andorra-latest.osm.pbf
Getting md5 checksum from https://download.geofabrik.de/europe/andorra-latest.osm.pbf.md5
Downloading https://download.geofabrik.de/europe/andorra-latest.osm.pbf (size=1.6 MB (1,665,170), md5=85a84f0dff17b80eb75eaca4653ba16b)

  aria2c --checksum=md5=85a84f0dff17b80eb75eaca4653ba16b --http-accept-gzip "--user-agent=OpenMapTiles download-osm 4.2.0 (https://github.com/openmaptiles/openmaptiles-tools)" --on-download-complete /usr/src/app/download-osm /import/last.state.txt -- -d /import https://download.geofabrik.de/europe/andorra-latest.osm.pbf
  Setting environment vars: DOWNLOAD_OSM_DC_FILE=/import/docker-compose-config.yml, OSM_AREA_NAME=europe/andorra, MIN_ZOOM=0, MAX_ZOOM=7, MAKE_DC_VERSION=2.3
  capturing stdout/stderr to wait for subprocess exit

Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: /import/last.state.txt


Creating Imposm config file /tileset/--state:
--------------------  ----------------------------------------------------
replication_url       https://download.geofabrik.de/europe/andorra-updates
replication_interval  24h
--------------------  ----------------------------------------------------

**Comment by frodrigo** [comment]
Same issue I have reported here https://github.com/openmaptiles/openmaptiles-tools/issues/246

**Comment by frodrigo** [comment]
On my side it does not get `last.state.txt`, but without error.

**Comment by frodrigo** [comment]
I make a PR to solve my issue, but it will not match your
https://github.com/openmaptiles/openmaptiles-tools/pull/251

**Comment by frodrigo** [comment]
Tyr to call the tool directly, play with params
```
docker-compose run openmaptiles-tools bash -c \
    "download-osm geofabrik ${AREA} \\
        --verbose \\
        --state /import/last.state.txt \\
        -- -d /import"
```

**Comment by toinouu** [comment]
Thx :)  

But i think i'll wait for a  stable version of openmaptiles
