### ISSUE TITLE
Openmaptiles commit does not exist: 522e5da1e3bf3b228ec9a00d98a4ffc954d2be09

### ISSUE THREAD

**Issue by henningvs** [makinacorpus/makina-maps#17]
Seems that the commit does not exist anymore:

```
fatal: remote error: upload-pack: not our ref 522e5da1e3bf3b228ec9a00d98a4ffc954d2be09
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'openmaptiles', but it did not contain 522e5da1e3bf3b228ec9a00d98a4ffc954d2be09. Direct fetching of that commit failed.
```

**Comment by frodrigo** [comment]
I will fix it.
For now you can use this branch
https://github.com/frodrigo/openmaptiles/tree/makina_maps_openmaptiles-tools-v5

**Comment by frodrigo** [comment]
Fixed. Sorry. The underlying OpenMapTiles move fast and need adjustment to make realtime rendering a reality.
