### ISSUE TITLE
Multiple countries

### ISSUE THREAD

**Issue by toinouu** [makinacorpus/makina-maps#18]
Hi,

I see that the project has been updated :)

But I have another problem.

In my project I need to have several countries (France and Belgium)

So I download  France and Belgium files and I merge them with osmium tool, 
it works very well but I don't know how to manage updates.

Is there a solution? or should I delete and re-create the database each time I want to update my france-belgium database ?

thanks for the help

**Comment by frodrigo** [comment]
The `imposm run` for update download diff to apply. But in your case your does not have diff for this area. You can:
1. produce diff and make this available in http to imposm, see openmaptiles/data/imposm-config.json and openmaptiles/data/last.state.txt
2. or, use imposm to import prepared diff, `imposm diff` from openmaptiles `make import-diff`

Personally I will setup 1., and merge diff with osmosis.

**Comment by toinouu** [comment]
it's a bit confusing for me.

How can I create this diff from my 2 countries?

**Comment by frodrigo** [comment]
The extract producer also provide diff like http://download.geofabrik.de/europe/andorra-updates/
You can merge probably with that https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#--merge-change_.28--mc.29

If you space and CPU, just use Europe ;-).

**Comment by toinouu** [comment]
ok so i did a test with 2 small countries (luxembourg + malta)

https://download.geofabrik.de/europe/malta-updates/000/002/623.osc.gz
https://download.geofabrik.de/europe/luxembourg-updates/000/002/622.osc.gz

I downloaded and merged these 2 files into 1 named "all.osc.gz" and I made them public at this address http://localhost:8080/updates/all.osc.gz

now when i run the update command i get this error
-> Unable to read last.state.txt:open /import/last.state.txt: no such file or directory

I understand that I need this file but what should I put in it?

**Comment by frodrigo** [comment]
The one from the data source
http://download.geofabrik.de/europe/luxembourg-updates/state.txt

**Comment by toinouu** [comment]
I have 2 sources 

http://download.geofabrik.de/europe/luxembourg-updates/state.txt
http://download.geofabrik.de/europe/malta-updates/state.txt

Randomly ?

**Comment by frodrigo** [comment]
Yes it is same. Use the same file naming.
