### ISSUE TITLE
JS Error and Vector Tiles  empty

### ISSUE THREAD

**Issue by toinouu** [makinacorpus/makina-maps#19]
![image](https://user-images.githubusercontent.com/503587/83136360-a12a1280-a0e7-11ea-8143-92675d9d508d.png)

**Comment by frodrigo** [comment]
What do you call "empty tiles"? The is a link with js error?

**Comment by toinouu** [comment]
Yes that's it, the link

**Comment by frodrigo** [comment]
JS error fixed.

But still not understood what do you call empty tiles.
