### ISSUE TITLE
[question] MakinaMaps behind traefik, serves styles with a wrong hostname

### ISSUE THREAD

**Issue by amenk** [makinacorpus/makina-maps#75]
We have Makina maps behind a traefik proxy,

out of a sudden, the styles.json contain the wrong URLs

```
Mixed Content: The page at 'https://africa.tiles.openplaceguide.org/#map=3/1.75/20.99' was loaded over HTTPS, but requested an insecure resource 'http://web.addismaptransit.com:8080/styles/bright/style.json'. This request has been 
```

Where can I configure the URL which should be referenced in the style.json ?

EDIT: I already tried to replace the $http_host variables in the nginx template and restarted:

```
            proxy_set_header Host africa.tiles.openplaceguide.org;
```

This did not help.

**Comment by frodrigo** [comment]
> I already tried to replace the $http_host variables in the nginx template and restarted:

It may be in cache.

The right move should be to forward host / proxy header in traefik I guess.

**Comment by amenk** [comment]
Thanks for the quick answer. @frodrigo 

```
docker volume rm makina-maps_nginx-cache
```

fixed it.

I guess I have some kind a race condition in the traefik config and depending on which container starts first, it get's confused. And then the wrong host was stored in nginx cache.

Thanks once again, also for this awesome project.
